# Generated by Django 5.1.1 on 2024-09-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='teachers',
        ),
    ]
