# Generated by Django 5.1.1 on 2024-10-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollmentrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnrollmentRequest',
        ),
    ]
