# Generated by Django 5.1.1 on 2024-10-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_discussionreply_content_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionreply',
            name='content_reply_to',
        ),
    ]
